### ISSUE TITLE
Idea for refactor versioning

### ISSUE THREAD

**Issue by afred** [samvera/samvera.github.io#203]
**Background:** the current system for creating multiple versions of documentation pages can be made easier with plugins, and a different conventions.

**Goals:**
  1. Each page should only need to contain version information about itself; not for all past and future versions as well.
  1. Associating multiple versions of a documentation page should not involve having to create folders to group pages of similar versions.
  1. Any version of a documentation page may be compatible with one or more Github branches, or Rubygem versions.
  1. All versions of a documentation page need not have their own entry the nav menu.

**How to create a new version of a documentation page (ideally):**
  1. Copy the latest version of the page (the one without any versioned suffix) to a file with a versioned suffix.

     For example:
      ```
      cp pages/my_tutorial.md pages/my_tutorial__1.0.md
      ```
  1. Update content for the latest version of the doc page (the one without the versioned suffix).
  1. _Optional:_ Override the default version label in the front matter.
     
     For example:
      ```yaml
      # in pages/my_tutorial.md
     version:
       # The default label would be "My Tutorial" (gleaned from the filename).
       # Here we can change it to include the latest version number.
       label: "My Tutorial 1.1" 
      ``` 

**Strategy:**
  1. Folders representing different versions are removed, and instead, documentation pages that are versions of each other are grouped by an easy-to-read file naming convention.

     For example, the following documentation pages would be versions of each other:
      - `pages/my_tutorial.md` _(latest version)_
      - `pages/my_tutorial__1.1.md`
      - `pages/my_tutorial__1.0.md`
      - `pages/my_tutorial__1.0_with_special_feature.md`

  1. Based on this filenaming convention, a plugin can be used to:
      1. Detect which doc pages are versions of each other, by matching the file name before the `__x.y.z.md suffix`
      1. Create a default label for the version of the doc page by title-izing the file name.
      1. Versions are ordered lexicographically by their version suffix.

  1. The plugin gathers information about all available versions of a given page, and adds that data to the page dynamically. The data is then made available on the Liquid object, as if it had been explicitly included in the page's front matter.

     For example, given the filenames above, each Liquid Page object would have version information as if the following had been entered manually in the page's front matter:
      ```yaml
      versions:
        - label : "My Tutorial"
           link" : 'pages/my_tutorial.md'
        - label: "My Tutorial 1.1"
           link: 'pages/my_tutorial__1.1.md'
        - label: "My Tutorial 1.0"
           link: 'pages/my_tutorial__1.0.md'
        - label: "My Tutorial 1.0 With Special Feature"
           link: 'pages/my_tutorial__1.0_with_special_feature.md'
      ```

**Done when:** new versions of existing documentation pages can be created using the **How to** steps above.
