### ISSUE TITLE
Create an 'include' for displaying links to Github wiki docs

### ISSUE THREAD

**Issue by afred** [samvera/samvera.github.io#370]
**Rationale:** during Docs WG breakout as Samvera Connect 2018, we discussed ways to better expose links to other documentation, in particular Github Wiki pages.

Not sure if there is already an "external links" feature in the current theme, so that's something to check.

If it exists, then let's explore it.

If it doesn't, then a reasonable way to go about this would be to...
  1. create a template at `_includes/external_links.html`
  1. The template uniformly calls out a set of links (most likely at the bottom of the page content)
     1. each link has a URL, a title, and `target="_blank"`.
  1. links are specified per-page in the front matter, with a clearly understood key that matches the template name, e.g...
      ```
      external_links:
        - url: "https://github.com/samvera/hyrax/wiki/Feature-matrix"
           title: "Hyrax Feature Matrix"
        - url: "https://github.com/samvera-labs/valkyrie/wiki"
           title: "Valkyrie Documentation"
      ```

**Done when:**
  1. content editors can easily, and uniformly, add links to other documentation to each page via front matter.
  1. Used in at least 1 page so approvers can see it working
